# Generated by Django 5.1.2 on 2024-10-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_minimum',
            field=models.IntegerField(default=5),
        ),
    ]
